// <auto-generated />
using System;
using CharityCalculator.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CharityCalculator.Persistence.Migrations
{
    [DbContext(typeof(CharityCalculatorDbContext))]
    partial class CharityCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharityCalculator.Domain.Models.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumDonationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SupplementInPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46c3a42c-e57c-4dd6-8d3f-a07049867d1d"),
                            DateCreated = new DateTime(2022, 2, 14, 21, 57, 13, 750, DateTimeKind.Local).AddTicks(5514),
                            LastModified = new DateTime(2022, 2, 14, 21, 57, 13, 751, DateTimeKind.Local).AddTicks(5079),
                            MaximumDonationAmount = 100000m,
                            Name = "Sports",
                            SupplementInPercentage = 5m
                        },
                        new
                        {
                            Id = new Guid("a1d9e128-a54c-4ac5-a8d4-cbb902f05d45"),
                            DateCreated = new DateTime(2022, 2, 14, 21, 57, 13, 751, DateTimeKind.Local).AddTicks(9720),
                            LastModified = new DateTime(2022, 2, 14, 21, 57, 13, 751, DateTimeKind.Local).AddTicks(9727),
                            MaximumDonationAmount = 100000m,
                            Name = "Political",
                            SupplementInPercentage = 3m
                        },
                        new
                        {
                            Id = new Guid("eaa00086-4626-4a46-8f7b-b4285e0b9950"),
                            DateCreated = new DateTime(2022, 2, 14, 21, 57, 13, 751, DateTimeKind.Local).AddTicks(9739),
                            LastModified = new DateTime(2022, 2, 14, 21, 57, 13, 751, DateTimeKind.Local).AddTicks(9740),
                            MaximumDonationAmount = 100000m,
                            Name = "Other",
                            SupplementInPercentage = 0m
                        });
                });

            modelBuilder.Entity("CharityCalculator.Domain.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RateInPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RateType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RateType")
                        .IsUnique();

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62ab6a74-e769-4f54-8e5c-5ef891d9b1f5"),
                            DateCreated = new DateTime(2022, 2, 14, 21, 57, 13, 771, DateTimeKind.Local).AddTicks(7164),
                            LastModified = new DateTime(2022, 2, 14, 21, 57, 13, 771, DateTimeKind.Local).AddTicks(7189),
                            RateInPercentage = 20m,
                            RateType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
